# Generated by Django 3.2.9 on 2022-04-29 05:03

import base.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_home_page_with_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ol', 'ul', 'link', 'document-link', 'br'], template='blocks/richtext_block.html')), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('video', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.CharBlock(required=True))])), ('horizontal_rule', base.blocks.HorizontalRuleBlock())], blank=True, verbose_name='Content'),
        ),
    ]
