# Generated by Django 3.2.9 on 2022-05-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_create_style_guide_page_and_fix_bugs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomImage',
        ),
    ]
