# Generated by Django 3.2.9 on 2022-05-04 04:19

import base.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_articlepage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='display_breadcrumbs',
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='content',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ol', 'ul', 'link', 'document-link', 'br'], template='blocks/richtext_block.html')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('video_block', wagtail.blocks.StructBlock([('url', wagtail.blocks.CharBlock(help_text='A link to a video on YouTube or Vimeo (eg https://www.youtube.com/embed/YE7VzlLtp-4).', required=True))])), ('card_list_block', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.blocks.CharBlock(required=False))])))])), ('accordion_block', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('content', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ol', 'ul', 'link', 'document-link', 'br'], template='blocks/richtext_block.html'))])))])), ('horizontal_rule', base.blocks.HorizontalRuleBlock())], blank=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ol', 'ul', 'link', 'document-link', 'br'], template='blocks/richtext_block.html')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('video_block', wagtail.blocks.StructBlock([('url', wagtail.blocks.CharBlock(help_text='A link to a video on YouTube or Vimeo (eg https://www.youtube.com/embed/YE7VzlLtp-4).', required=True))])), ('card_list_block', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.blocks.CharBlock(required=False))])))])), ('accordion_block', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('content', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ol', 'ul', 'link', 'document-link', 'br'], template='blocks/richtext_block.html'))])))])), ('horizontal_rule', base.blocks.HorizontalRuleBlock())], blank=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='content',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ol', 'ul', 'link', 'document-link', 'br'], template='blocks/richtext_block.html')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('video_block', wagtail.blocks.StructBlock([('url', wagtail.blocks.CharBlock(help_text='A link to a video on YouTube or Vimeo (eg https://www.youtube.com/embed/YE7VzlLtp-4).', required=True))])), ('card_list_block', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.blocks.CharBlock(required=False))])))])), ('accordion_block', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('content', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'ol', 'ul', 'link', 'document-link', 'br'], template='blocks/richtext_block.html'))])))])), ('horizontal_rule', base.blocks.HorizontalRuleBlock())], blank=True, verbose_name='Main Content'),
        ),
    ]
