# Generated by Django 4.0.4 on 2022-05-09 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StyleGuidePage',
        ),
    ]
